// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ReceiptsWebBlazor.Components.Pages;
using System;
using System.Collections.Generic;

namespace ReceiptsWebBlazor.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Group { get; set; }

    public decimal Price { get; set; }

    public DateTime DateReceipt { get; set; }

    public string SourceName { get; set; }

    public int SourceLine { get; set; }

    public string FullData { get; set; }
}
