<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>JPEG128emboss3x3.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="JPEG128emboss3x3.ico" />
  </ItemGroup>

</Project>