// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASPCoreWebAppMVC.Models;

public partial class Author
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Book> Book { get; set; } = new List<Book>();
}