// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASPCoreWebAppMVC.Models;

public partial class Book
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Note { get; set; }

    public int? Author { get; set; }

    public virtual Author AuthorNavigation { get; set; }

    public virtual ICollection<Borrowed> Borrowed { get; set; } = new List<Borrowed>();
}