// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASPCoreWebAppMVC.Models;

public partial class Borrowed
{
    public int Id { get; set; }

    public int BookId { get; set; }

    public DateTime? Date { get; set; }

    public virtual Book Book { get; set; }
}